### ISSUE TITLE
수동 동기화에 대해서 (run gbt)

### ISSUE THREAD

**Issue by skyoon1109** [dc-koromo/e-archive#3]
커맨드 창 열고 run gbt라고 입력 했는데 
 Forbidden. You cannot use gbt tool.
이라고 뜨네요. 어떡해야 하나요?

**Comment by ghost** [comment]
데이터 관리가 불가능해질 시점이 오면
그때 차단풀어서 마지막으로 업데이트해두도록 하겠습니다.
